### ISSUE TITLE
CI beüzemelése, Travis

### ISSUE THREAD

**Issue by KZsolt11** [KZsolt11/coins-android#1]
KZsolt11 & Farkas25 felhasználók oldották meg a feladatot.
https://github.com/KZsolt11/coins-android/commit/7d89edd384683ce4caf7c908642719cf354e3e30
https://github.com/KZsolt11/coins-android/commit/b25ed5c24e268616a52ab69f2c66130e053f23ca
https://github.com/KZsolt11/coins-android/commit/ce5e6379945881d5933cbcb55d147a82b1a45767
https://github.com/KZsolt11/coins-android/commit/694a50989bb2c5bc9a4735139d2a2f91ae24a084

**Comment by Farkas25** [comment]
Ellenőriztem. A megoldás helyes.

**Comment by KZsolt11** [comment]
Köszönöm!

**Comment by Farkas25** [comment]
Nem, én köszönöm a nagyszerű munkát.

**Comment by micskeiz** [comment]
Csak a chmod-dal futtatási jogot adtok, de utána nem hívjátok meg a gradlew parancsot. Így, bár a build sikeres, de nem csinálja meg a fordítást ténylegesen.
